/**
 * Errors out to a 404 page
 * @param {Object} req Request object by user
 * @param {Object} res Response object to request
 * @param {Function} next Moves on to next function in express chain
 */
const notFound = (req, res, next) => {
  const error = new Error(`Not Found - ${req.originalUrl}`)
  res.status(404)
  next(error)
}

/**
 * Handles an error generated by chain
 * @param {Object} err Error happended
 * @param {Object} req Request object by user
 * @param {Object} res Response object to request
 */
const errorHandler = (err, req, res) => {
  const statusCode = res.statusCode === 200 ? 500 : res.statusCode
  res.status(statusCode)
  res.json({
    message: err.message,
    stack: err.stack,
  })
}

module.exports = { notFound, errorHandler }
